### ISSUE TITLE
Support non-S3 path (MinIO-like)

### ISSUE THREAD

**Issue by devlopesbernardo** [Clivern/Walrus#114]
**Is your feature request related to a problem? Please describe.**
I've tested the farthest that I was able to - but I couldn't get [**MinIO**](https://min.io/) to work with Walrus - after loads of debug (public/download policies, IP/port change, new access key/secret, etc, I was not able to use MinIO with Walrus.

I was also not able to find the reason why on the logs - but if you advise me how to find, I'll try my head to send it all here and send you.

**Describe the solution you'd like**
MinIO, by default, uses:
hostname.tld/bucket-name/object-name, while S3 uses something like bucket-name.hostname.tld/object-name.

Thus, a great way would be to add a switch or a case, if possible, for both situations.

If I'm mistaken, I'm looking forward to correct soon enough - and also contribute to the project if possible! 😄

**Comment by Clivern** [comment]
Thanks for the testing @devlopesbernardo! Amazon s3 sdk creates `bucket-name.hostname.tld/object-name` and it seems it doesn't work with minIO. But there is an option to force the use of `hostname.tld/bucket-name/object-name` which is `S3ForcePathStyle` https://github.com/aws/aws-sdk-go/blob/master/aws/config.go#L127

so updating these lines https://github.com/Clivern/Walrus/blob/main/core/storage/s3.go#L31-L37 to

```
    return &S3{
        config: &aws.Config{
            Credentials: credentials.NewStaticCredentials(key, secret, ""),
            Endpoint:    aws.String(endpoint),
            Region:      aws.String(region),
            S3ForcePathStyle: aws.Bool(true),
        },
    }
```
seems solved the issue. I have to 2 options
1. Add `S3ForcePathStyle` by default if it will work with minIO, AWS S3 and Digitalocean Spaces (have to test that).
2. Add option in the dashboard to identify if s3 uses path style or virtual host style and let users decide.

**Comment by devlopesbernardo** [comment]
Hey! Thanks for the quick response, @Clivern! Hope that you're feeling nice today =)

I can provide accesses to minIO, S3 and Spaces for manual testing, however I do not really understand a lot of Go to automatically test it (but should be enough to manually test it).

So, for 1:
I should clone the repo, test it with this platforms, working, submit a PR?

For 2, how does this change would affect the backend?

I will dig further into the code asap to understand it better - this is my first contributtion on open source software, so I'm looking for corrections when they're needed :metal:

**Comment by Clivern** [comment]
For the first option, All you need is to add this config value `S3ForcePathStyle` & test with different s3 providers.

Here is all you need to change & test:

- Clone on github then clone locally.
- Install golang on your laptop. 
- Run etcd locally on ubuntu with this command `./bin/local_etcd_ubuntu.sh` or this `./bin/local_etcd_mac.sh` on mac.
- Change walrus go code.
- To run the tower locally, run `make run_tower` then visit http://127.0.0.1:8000, install and update settings page with s3 configs.
- To run the agent locally, run `make run_agent`.
- Backup a file from your laptop to s3 & check logs.
- Run code checks with `make ci` before pushing into github


Needed for Option Two (UI Changes): 
You will need nodejs & npm since it is a single page application uses Vuejs. Here is all you need to run the frontend application or to package it in go code.

```bash
$ cd web

# Install packages
$ npm install
$ npm install -g npx

# add tower url to frontend
$ echo "VUE_APP_TOWER_URL=http://127.0.0.1:8000" > .env

$ cd ..

# Run frontend 
$ make serve_ui

# To bundle the frontend into go application
$ make package
```

**Comment by devlopesbernardo** [comment]
I'm really grateful for your detailed guide. I do have all of this installed, since I've messed around with go for a while and work on freelacing nodejs.

I will try it as soon as possible. Hope to buy you a beer anytime :beers:
