### ISSUE TITLE
More documentation, examples and screenshots

### ISSUE THREAD

**Issue by muety** [Clivern/Walrus#283]
Hi, I just randomly discovered this project and at first sight it looks super interesting! However, it would be cool to have some more details on what Walrus is actually capable of, how to configure it and a few more screenshots of the admin UI. This would help people get a better idea of this tool might be helpful for theit use cases without having to go through the whole setup process to create a personal demo instance. 

For instance, a few questions that came to my mind browsing the readme include:
* How does it "look" like to configure new backup jobs of different types, e.g. file system backup, MySQL backup, etc.?
* Are backups incremental and are they compressed?
* Can you easily restore backups?
* Is this project still under active development and what is the roadmap?
* How does Walrus compare to tools like Restic, Borg, etc.?

**Comment by Clivern** [comment]
Hi @muety,

It is maintained. i can't really run dedicated demo but it is handy to run it locally. 

```bash
$ git clone https://github.com/Clivern/Walrus.git
$ cd Walrus

# Run local etcd
$ ./bin/local_etcd_mac.sh

$ make run_tower
```
From UI `http://127.0.0.1:8000`, install the tower. once you run agents on hosts with the right tower url & credentials, it will show up in UI and you can setup backups for these hosts.

Or you can run with docker-compose https://github.com/Clivern/Walrus/tree/main/deployment/docker-compose

- Restore not supported so far.
- Restic is a nice tool, i used it a lot. it supports many storage backends. so it totally up to you, if walrus fits your use case, use it otherwise i would recommend restic or duplicacy.
